package Entities;
// Generated 03-jul-2017 14:58:13 by Hibernate Tools 4.3.1



/**
 * Comment generated by hbm2java
 */
public class Comment  implements java.io.Serializable {


     private int idComment;
     private User user;
     private String description;
     private String objectType;
     private int idObject;

    public Comment() {
    }

    public Comment(int idComment, User user, String description, String objectType, int idObject) {
       this.idComment = idComment;
       this.user = user;
       this.description = description;
       this.objectType = objectType;
       this.idObject = idObject;
    }
   
    public int getIdComment() {
        return this.idComment;
    }
    
    public void setIdComment(int idComment) {
        this.idComment = idComment;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getObjectType() {
        return this.objectType;
    }
    
    public void setObjectType(String objectType) {
        this.objectType = objectType;
    }
    public int getIdObject() {
        return this.idObject;
    }
    
    public void setIdObject(int idObject) {
        this.idObject = idObject;
    }




}


