package Entities;
// Generated 03-jul-2017 14:58:13 by Hibernate Tools 4.3.1



/**
 * Photo generated by hbm2java
 */
public class Photo  implements java.io.Serializable {


     private int idPhoto;
     private Mockup mockup;
     private byte[] file;
     private String fileType;

    public Photo() {
    }

    public Photo(int idPhoto, Mockup mockup, byte[] file, String fileType) {
       this.idPhoto = idPhoto;
       this.mockup = mockup;
       this.file = file;
       this.fileType = fileType;
    }
   
    public int getIdPhoto() {
        return this.idPhoto;
    }
    
    public void setIdPhoto(int idPhoto) {
        this.idPhoto = idPhoto;
    }
    public Mockup getMockup() {
        return this.mockup;
    }
    
    public void setMockup(Mockup mockup) {
        this.mockup = mockup;
    }
    public byte[] getFile() {
        return this.file;
    }
    
    public void setFile(byte[] file) {
        this.file = file;
    }
    public String getFileType() {
        return this.fileType;
    }
    
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }




}


